### PR TITLE
Detect if /system is f2fs partition. Detect /cache partition type

### PR DESCRIPTION
**Pull request by yurem**

### CODE REVIEW

**Comment by that1** [comment]
I incorporated your suggestions, but I cleaned up the code first (yours and mine). Please test if it works, I didn't. :)

**Comment by yurem** [comment]
The init code looks fine for me

**Comment by yurem** [comment]
I tested it. It works fine.

**Comment by yurem** [comment]
I hope that you will include it in new kernel :)

**Pull request closed without merging**
